---
title: <small>An introduction to digital open <br>research in clinical psychology</small>
author: <small>Matthias Weiler</small>
date: <small>22.03.2018</small>
output:
  revealjs::revealjs_presentation:
    theme: black
    center: TRUE
    self_contained: FALSE
    incremental: TRUE
    reveal_plugins: ["chalkboard"]
    reveal_options:
      chalkboard: 
      readonly: FALSE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# <small> What we did last <s>week</s> time</small>

----

We talked about your <br>
personal open science projects

----

Then we talked about <br>
tools you can use in your <br>
personal science projects

----

And finally you started to <br>
work on your research proposals

----

Any questions or anything to add?

# <small>Last <s>week's</s> session's homework</small>

----

Who of you prepared a <br>
presentation for today?

----

Who of you sent a pdf <br>
version of your presentation <br>
to your instructor?

----

Who of you uploaded your <br>
presentation to the OSF?

----

Any questions regarding <br>
last time's homework?

# <small>Today:<br>Present and review your research proposals</small>

# <small>Basic rules for your presentation</small>

----

You only have 5 minutes <br>
for your presentation

----

You will be notified before <br>
the final minute starts

----

You have 3 additional minutes <br>
to answer questions

----

Any questions?

# <small>Proposal reviews</small>

----

Choose your favorite project <br>
(one from each university)

----

Write it down on a piece of paper <br>
(one for each university)

----

The two projects from each <br>
university with the most votes <br>
will "win" (final projects)

----

Any questions?

# <small>Research groups</small>

----

Research will be done in mixed groups <br>
(with students from each university)

----

If your project was not chosen <br>
as a final project, you will work in <br>
a project from the other university

----

Any questions?

# <small>Running order</small>

----

1: Christina Ioanna Schoina <br>
2: Ioanna Falegka <br>
3: Anastasios Tsilingiris <br>
4: Erasmia Kaminari <br>
5: Malamatenia Karvouniari <br>

----

Short break (10 minutes)

----

6: Marianna Zachou <br>
7: Valliano Rokai <br>
8: Kyriaki Lazaki <br>
9: Eleni Rigina Vouloumanou <br>
10: Vaia Sideropoulou <br>

----

Short break (10 minutes)

----

11: Fotios Ntagkas <br>
12: Stavroula Blazaki <br>
13: Eleni Boutiou <br>
14: Katerina Dimitriadou <br>
15: Chrysoyla Kampadai 


# <small>Let's go</small>

----


1: Christina Ioanna Schoina <br>
(next: Ioanna Falegka)

----

2: Ioanna Falegka <br>
(next: Anastasios Tsilingiris)

----

3: Anastasios Tsilingiris <br>
(next: Erasmia Kaminari)

----

4: Erasmia Kaminari <br>
(next: Malamatenia Karvouniari)

----

5: Malamatenia Karvouniari <br>
(next: Marianna Zachou)

----

## <small>Short break (10 minutes)</small>

----

6: Marianna Zachou <br>
(next: Valliano Rokai)

----

7: Valliano Rokai <br>
(next: Kyriaki Lazaki)

----

8: Kyriaki Lazaki <br>
(next: Eleni Rigina Vouloumanou)

----

9: Eleni Rigina Vouloumanou <br>
(next: Vaia Sideropoulou)

----

10: Vaia Sideropoulou <br>
(next: Fotios Ntagkas)

----

## <small>Short break (10 minutes)</small>

----

11: Fotios Ntagkas <br>
(next: Stavroula Blazaki)

----

12: Stavroula Blazaki <br>
(next: Eleni Boutiou)

----

13: Eleni Boutiou <br>
(next: Katerina Dimitriadou)

----

14: Katerina Dimitriadou <br>
(next: Chrysoyla Kampadai)

----

15: Chrysoyla Kampadai 

# <small>Great job!</small>

# <small>Choose the final projects</small>

----

Choose your favorite project <br>
(one from each university)

----

Write it down on a piece of paper <br>
(one for each university)

----

Give your vote to your instructor

# <small>Choose your research group</small>

----

Write your name on a piece of paper

----

Add the two projects from the other <br>
university in your order of preference <br>
(1. favorite, 2. second favorite)

----

Give your vote to your instructor

# <small>Preview: next week</small>

----

"Data collection / research"  

<i>No course!</i>

----

I will sent you links to the projects

# <small>Preview: next session</small>

----

On Wednesday, 25th of April

----

"Present your project results"

# <small>Homework</small>

----

Start collecting data

----

Participate in every project

----

Prepare your posters for <br>
the final presentation

# <small>Any questions?</small>

# <small>Thank you for your attention</small>
